### PR TITLE
Pavel Session: Message stack - part 1

### PR DESCRIPTION
**Pull request by ppavels**
https://docs.google.com/document/d/1TwjxKQSmt0fy-TWavgQv_JJtNGTHwFAVKNBtqSGTzwU/edit

### CODE REVIEW

**Comment by liatsade** [comment]
@ppavels here are my comments and things need to be fixed:

1/ Pay attention to the requirement in the exercise:

> Accordance with the client's request, the comment title can’t be edit after creating a comment. Use the right Token.

edit_comment___exercise

2/ Message module does not provide a way to create messages. You need to implement the relevant hook for that. Look at `message_example.module` for example how it should be implemented.

3/ I can't find your View (part 2 in the exercise), please mention the name and the path of the view.

4/ Please add screenshots of the main result of your work.

**Comment by liatsade** [comment]
@ppavels are you going to finish this?

**Comment by ppavels** [comment]
@liatsade Sure, today.

**Comment by ppavels** [comment]
selection_584

**Comment by ppavels** [comment]
selection_583

**Comment by liatsade** [comment]
Good, you used the right token and implement the right hook, but the view is not correct. 
Please look at the exercise requirement:

> Display **only messages** that belong to the message type you created.
> Add the option for the user (expose filter) to filter the content by the **node type**.

**Comment by ppavels** [comment]
`http://localhost/drupal7/www/comment-message`

selection_589

**Comment by liatsade** [comment]
@ppavels is it ready for review?

**Comment by ppavels** [comment]
@liatsade yes, ready for review. Thanks.

**Comment by liatsade** [comment]
Now it is perfect :-)

**Comment by ppavels** [comment]
@liatsade Thanks :)

**Pull request closed without merging**
