### PR TITLE
WIP:YM message exercise part 1

### PR DESCRIPTION
**Pull request by Yonimdo**

### CODE REVIEW

**Comment by Yonimdo** [comment]
### Update:

still no content on page, Needs tests

**Comment by liatsade** [comment]
@MoodyUser see my comments:

1/ This is not the right way to use tokens. Please fix.
Pay attention to the requirement in the exercise:

> Accordance with the client's request, the comment title can’t be edit after creating a comment. Use the right Token.

edit_user_comment_on_post___exercise

2/ I can't find your View (part 2 in the exercise), please mention the name and the path of the view.

3/ Please add screenshots of the main result of your work.

4/ Please Assign me when you are done.

@amitaibu please review the hook_comment_insert implementation:
ym_message_stack_p1_module_-_message-stack_-____sites_message-stack_

**Comment by liatsade** [comment]
@MoodyUser sorry, now I see you add WIP :-)
Update when you are done.

**Comment by liatsade** [comment]
@MoodyUser are you going to finish this?

**Comment by MoodyUser** [comment]
@liatsade Yes. I'm planning on finishing this assignment until the end of this week.

**Pull request closed without merging**
