### PR TITLE
Davidb message exercise

### PR DESCRIPTION
**Pull request by DavidBronfen**
https://docs.google.com/document/d/1TwjxKQSmt0fy-TWavgQv_JJtNGTHwFAVKNBtqSGTzwU/edit

### CODE REVIEW

**Comment by DavidBronfen** [comment]
@liatsade 
This is the view i created, everything looks OK,
One thing only i can't set the message type to be new_comment (as i set when i created the message),
they are all set as example create comment.

This is the hook comment insert code:
selection_005

This is the view i'm getting:
selection_003

**Comment by liatsade** [comment]
@DavidBronfen here are my comments and things need to be fixed:

> One thing only i can't set the message type to be new_comment (as i set when i created the message),

you did it right:
comment_messages__message____exercise
1. Your module called "exercise_message" but in the dependencies you wrote "message_exercise". 
   Of course such mistakes can happen, but if you do re-install of Drupal as a test to check if your module works, you will find the error immediately.
   exercise_info_-_message-stack_-____sites_message-stack_
2. The message needs to be also in Hebrew and English. You need to export the language as part of the feature.
3. Pay attention to the requirement in the exercise:

> Accordance with the client's request, the comment title can’t be edit after creating a comment. Use the right Token.

edit_new_comment___exercise

Please add screenshots of the main result of your work.

**Comment by DavidBronfen** [comment]
@liatsade 
OK i got it. 

This is my final (hopefully) result.

selection_005

**Comment by liatsade** [comment]
Now it's great :-)

**Pull request closed without merging**
