### PR TITLE
Message exercise part 1

### PR DESCRIPTION
**Pull request by savyoncohen**
@liatsade 
Hi, 
this is my Exercise PR.

### CODE REVIEW

**Comment by liatsade** [comment]
@savyoncohen here are my comments and things need to be fixed:
1. Message type description is human-readable so it should begin with capital letter
   edit_user_commented_on_a_node___exercise
2. The message should be in English and Hebrew. You create Message type only in English.
3. I see this comment in your module, but I don't see where you implement this in your code.
   message_exercise_module_-_message-stack_-____sites_message-stack_
4. @amitaibu I'm not sure about this, please review.
   I think for `field_node_ref` we should set `$node`
   and for `field_comment_ref` we should set only `$comment`
   but maybe what @savyoncohen did is also right:
   message_exercise_module_-_message-stack_-____sites_message-stack_
5. I can't find your View (part 2 in the exercise), please mention the name and the path of the view. 
6. Please add screenshots of the main result of your work.

**Comment by savyoncohen** [comment]
My View: 
selection_013
Message in hebrew and english:
selection_014
selection_015

**Comment by savyoncohen** [comment]
@liatsade 
1. Fixed.
2. Fixed - I exported the language settings.
3. I removed this comment, it's was taken from the message example module that i used.
5. The view url is 'comments-messages'.
6.Screenshots were added.

**Comment by amitaibu** [comment]
> @amitaibu I'm not sure about this, please review.
>  think for field_node_ref we should set $node

The wrapper allows us to set the node object _or_ the node ID.

btw, PR needs a re-roll

**Comment by liatsade** [comment]
Now it is good :-)

> 1. Fixed - I exported the language settings.

I checked the detection in the Local module, and you were right, it is not "featureble".

**Pull request closed without merging**
