### PR TITLE
Session: Message stack - part 1

### PR DESCRIPTION
**Pull request by nirgn975**

### CODE REVIEW

**Comment by liatsade** [comment]
@nirgn975 here are my comments and things need to be fixed:

1/ Pay attention to the requirement in the exercise:

> Accordance with the client's request, the comment title can’t be edit after creating a comment. Use the right Token.

edit_comment___exercise

2/ Your view is not exactly as require.

> Display only messages that belong to the message type you created.

It is not supposed to be exposed.
comment_message__message____exercise

> Add the option for the user (expose filter) to filter the content by the node type.

You missed that one.

3/ Please add screenshots of the main result of your work.

4/ Please assign me when you're done

**Comment by nirgn975** [comment]
The view:
exercise

The comment:
ev___exercise

The message type:
edit_comment___exercise
edit_comment___exercise

**Comment by nirgn975** [comment]
@liatsade You are very right, didn't notice all of that, sorry.
Now it's ready for review.

**Comment by liatsade** [comment]
Ok, you almost there :-)
This part is still missing in the view:

> Add the option for the user (expose filter) to filter the content by the node type.

**Comment by liatsade** [comment]
@nirgn975 are you going to finish this?

**Comment by nirgn975** [comment]
@liatsade Yep. Today (I think).

**Comment by nirgn975** [comment]
@liatsade I add it, I think it's what you meant.

**Comment by liatsade** [comment]
Yes, now it's good :-)

**Pull request closed without merging**
